services:
    app:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: scrum-app
        ports:
          - "8080:80"
        volumes:
          - ./:/var/www/html
    mariadb:
      image: mariadb:10.5
      container_name: mariadb-scrum
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: scrum_project
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      ports:
        - "3306:3306"
      volumes:
        - ./db:/var/lib/mysql
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: phpmyadmin-scrum
      environment:
        PMA_HOST: mariadb
        PMA_USER: root
        PMA_PASSWORD: root
      ports:
        - "8081:80"
      depends_on:
        - mariadb
    ollama:
      image: docker.io/ollama/ollama:latest
      container_name: ollama-scrum
      ports:
        - "8082:80"
      volumes:
        - ./:/usr/src/app
      pull_policy: always
      tty: true
